image: maven:latest


stages:
  - build
  - test
  - package

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn -f TourGuide/pom.xml clean compile

test:
  stage: test
  script:
    - mvn -f TourGuide/pom.xml test

package:
  stage: package
  script:
    - mvn -f TourGuide/pom.xml package
  artifacts:
    paths:
      - TourGuide/target/*.jar
